### ISSUE TITLE
lbl_relabel without requiring x to be a labelled variable

### ISSUE THREAD

**Issue by chengchou** [mnpopcenter/ripums#51]
`lbl_relabel(x, ...)` is very useful for creating a new labelled variable by changing the labels of `x` via formulas or lambda functions. It is particularly useful when the label has a clear rule. The issue is that `lbl_relabel` requires that `x` is a labelled object. 
When `x` is a just vector, one needs to assign a label to each of its possible values using `labelled` function. This could be inconvenient because `labelled` function does not support label by formulas/lambda functions. It would be handy to allow `lbl_relabel` to operate on an unlabelled vector. I created a new function called `lbl_define(x, ...)` based on `lbl_relabel`. It works exactly like `lbl_relabel` excepting for that `x` is just a numeric or character vector.

Here is one example. Suppose

```
age <- c(10, 14, 16, 19, 22)
```

I want to assign the label "age before college" to the ages <= 18 (i.e., 10, 14, and 16), and assign the label "college age" to the ages > 18 (i.e., 19 and 22).  Using `lbl_define`, we can need

```
lbl_define(age,
  lbl(1, "age before college") ~ .val <= 18,
  lbl(2, "college age") ~ .val > 18
  )
```

Here is the output the above lines,

```
<Labelled double>
[1] 1 1 1 2 2

Labels:
 value              label
     1 age before college
     2        college age
```

Below is the code of `lbl_define`:
```
lbl_define <- function (x, ...) {
  # x is a vector to be labelled.
  # Add naive label
  x.lbled <- haven::labelled(x, NULL)
  for (xx in unique(x)) {
    val_label(x.lbled, xx) <- paste0('lbl: ', xx)
  }
  lbl_relabel(x.lbled, ...)
}
```

**Comment by dtburk** [comment]
Thanks for the thoughtful suggestion @chengchou! I'd be open to adding this functionality to the package, and `lbl_define` seems like a good name to me. We would probably want to use `ipumsr::lbl_add()` instead of `labelled::val_lbl()` to avoid an additional dependency. Any objections @gergness?

**Comment by gergness** [comment]
Makes sense to me as well. This does stray a little from the primary purpose of ipumsr - to work with IPUMS data, which generally already has value labels attached - but it's not too much extra code, and I do agree that it is useful in certain situations, so I'd say go for it.

You could also consider trying to use S3 methods so that `lbl_relabel()` would work with objects that don't already have labels defined. I'm not sure which approach is cleaner.

**Comment by dtburk** [comment]
I've created a new function `lbl_define()` on the "lbl_define" branch. I opted for this approach instead of using S3 methods partly for my own convenience, but also because I think it better expresses intent. @chengchou feel free to install the branch with `remotes::install_github("mnpopcenter/ipumsr", ref = "lbl_define")` and let us know what you think.

**Comment by chengchou** [comment]
@dtburk The new `lbl_define` looks neat to me.  I think this function will be useful in some situations, since the other packages handling labels do not support labelling a vector by lambda functions. Thanks for considering my comment.
