### ISSUE TITLE
lower_vars not making variable names lowercase

### ISSUE THREAD

**Issue by hrecht** [mnpopcenter/ripums#56]
Hello, I'm having an issue with the lower_vars argument in read_ipums_micro(). It isn't having any effect. I've tried TRUE and T, and the variable names returned are still uppercase. No error message is given.

`dt <- read_ipums_micro(ddi, lower_vars = T)`

**Comment by dtburk** [comment]
Thanks for filing this issue, I agree this is confusing behavior. The reason the `lower_vars` argument is having no effect is to avoid converting the variable names in the data to lowercase if they are not lowercase in the DDI object. The documentation for argument `lower_vars` in function `read_ipums_micro()` indicates that the argument is operative "If reading a DDI from a file". If the `ddi` argument to `read_ipums_micro()` is an `ipums_ddi` object rather than a file path (meaning the user has already read in the DDI, as appears to be your situation), the `lower_vars` argument to `read_ipums_micro()` is ignored. You can get lowercase variable names by specifying `lower_vars = TRUE` in your call to `read_ipums_ddi()` when you read in the DDI, as in the example code below.

Here are the changes I propose in light of this confusing behavior. The current argument description for `lower_vars` in the documentation for `read_ipums_micro()` is: "If reading a DDI from a file, a logical indicating whether to convert variable names to lowercase (default is FALSE due to tradition)". I propose appending the following warning to this argument description: "Note that this argument will be ignored if argument `ddi` is an `ipums_ddi` object rather than a file path. See `\code{\link{read_ipums_ddi}}` for converting variable names to lowercase when reading in the DDI." I also propose throwing a warning when a user supplies an `ipums_ddi` object to `read_ipums_micro()` _and_ specificies `lower_var = TRUE`. @hrecht, do these proposed changes seem appropriate to you?

Below is code reproducing the confusing behavior, as well as the workaround for converting to lowercase when reading in the DDI.

``` r
library(ipumsr)
#> Registered S3 methods overwritten by 'ipumsr':
#>   method                                 from 
#>   format.pillar_shaft_haven_labelled_chr haven
#>   format.pillar_shaft_haven_labelled_num haven
#>   pillar_shaft.haven_labelled            haven
ddi <- read_ipums_ddi(ipums_example("cps_00006.xml"))
data <- read_ipums_micro(ddi, lower_vars = TRUE)
#> Use of data from IPUMS-CPS is subject to conditions including that users should
#> cite the data appropriately. Use command `ipums_conditions()` for more details.
names(data)
#> [1] "YEAR"     "SERIAL"   "HWTSUPP"  "STATEFIP" "MONTH"    "PERNUM"   "WTSUPP"  
#> [8] "INCTOT"
ddi <- read_ipums_ddi(ipums_example("cps_00006.xml"), lower_vars = TRUE)
data <- read_ipums_micro(ddi)
#> Use of data from IPUMS-CPS is subject to conditions including that users should
#> cite the data appropriately. Use command `ipums_conditions()` for more details.
names(data)
#> [1] "year"     "serial"   "hwtsupp"  "statefip" "month"    "pernum"   "wtsupp"  
#> [8] "inctot"
sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Debian GNU/Linux 9 (stretch)
#> 
#> Matrix products: default
#> BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] ipumsr_0.4.2
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3       xml2_1.2.2       knitr_1.26       magrittr_1.5    
#>  [5] hms_0.5.2        tidyselect_1.0.0 R6_2.4.1         rlang_0.4.4     
#>  [9] stringr_1.4.0    highr_0.8        dplyr_0.8.4      tools_3.6.1     
#> [13] xfun_0.11        htmltools_0.4.0  yaml_2.2.0       digest_0.6.23   
#> [17] assertthat_0.2.1 tibble_2.1.3     crayon_1.3.4     purrr_0.3.3     
#> [21] vctrs_0.2.2      zeallot_0.1.0    glue_1.3.1       evaluate_0.14   
#> [25] haven_2.2.0      rmarkdown_1.18   stringi_1.4.3    compiler_3.6.1  
#> [29] pillar_1.4.3     forcats_0.4.0    hipread_0.2.1    pkgconfig_2.0.3
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hrecht** [comment]
Hi @dtburk, confusing indeed. Thanks for the info. I'd recommend adding a usage example and instructions. The examples in the ipumsr vignettes show using read_ipums_micro on a ddi object, not a file path. 

Ideally, the best solution would be to simplify the behavior. Is there a reason read_ipums_micro shouldn't make variable names lowercase on a ddi object?

**Comment by dtburk** [comment]
I agree that it is not ideal that this argument is ignored when `read_ipums_micro()` is called on a ddi object, because that is the workflow we recommend in the vignettes, as you note.

However, the challenge with allowing `read_ipums_micro()` to make variable names lowercase in the ddi object is that it would require modifying the ddi object in the calling environment, as a side-effect of the function, since `read_ipums_micro()` only returns the data and not a ddi object. I've personally never seen that kind of behavior in an R function, though I suppose it is possible with the `<<-` assignment operator. 

@hrecht do you think a warning from `read_ipums_micro()` explaining why `lower_vars = TRUE` is being ignored, and urging the user to re-read the ddi with `lower_vars = TRUE`, would be insufficient or annoying? If users want to have the ddi object in their workspace (which we recommend), and they want lowercase variable names, I think we want to encourage a workflow in which the user sets `lower_vars = TRUE` when they read in the DDI, before reading in the data. The warning from `read_ipums_micro()` might be annoying the first time, but hopefully it would nudge the user in the direction of this desired workflow, which would then become habitual. This approach seems preferable to modifying an object that the user has not asked us to modify, but I am certainly open to counter-arguments. @gergness do you have an opinion?

**Comment by hrecht** [comment]
It seems that putting lower_vars = TRUE as an argument of read_ipums_ddi() instead of read_ipums_micro() would make the most sense. If that can be well documented that seems best. When I was trying to use it I didn't realize that was an option.

On a side note, it would be great if you could put the package site into this repo's website field in the description. That would make it a lot easier to find!

**Comment by dtburk** [comment]
@hrecht Thanks very much for this feedback, and for the tip about the package site -- it sometimes takes me a minute to find it too! I will follow your example with censusapi and put it right at the top of the repo landing page.

**Comment by gergness** [comment]
Yeah, agree this behavior isn't ideal :( 

A warning could work and seems way better than current behavior.

I definitely used to think it was important to have the names in the DDI match the names in loaded dataset, but I don't totally remember why and if they were good reasons. Might be worth just converting the variable names for the user anyways, and some of the metadata connecting features may not work as well but I'm not sure how often those are used. 

I'm thinking you could have something like `dplyr::rename_all(tolower)` as the last step in `read_ipums_micro()` (if `lower_vars ==TRUE`). It's been a while since I've been in the code though, so I may be forgetting something that would break

**Comment by hrecht** [comment]
Thanks for looking into this! A warning would help for sure.

**Comment by dtburk** [comment]
I closed this issue, since we added a warning and improved documentation, but I've also created a new issue (#59) as a reminder that we should probably make changes that will allow users to convert variable names to lowercase when they read in the data, even if they have already read in the DDI.

**Comment by hrecht** [comment]
thanks for tackling this!
